//server.js
const express = require('express'),
        server = express(),
        Sound = require('node-aplay'),
        path = require('path');
var count = 0;

var portNum = 3000;

server.use(express.static(path.join(__dirname, 'public')));

//setting the port.
server.set('port', process.env.PORT || portNum);

//Adding routes
server.get('/',(request,response)=>{
        console.log('Success');

        //play sound
        var tone = new Sound('2000.wav').play();

        response.sendFile(path.join(path.join(__dirname, 'views'), 'index.html'));
});

server.get('/test' ,(request,response)=>{
        console.log('Success');

        //play sound
        var tone = new Sound('2000.wav').play();

        response.status(200);
});

server.get('/playsound', (request, response)=>{
        console.log('Success');

        //play sound
        count++;
        var sound1 = 'sounds/Dog Whistle-SoundBible.com-118475604.wav';
        var sound2 = 'sounds/example.wav'; //generated by c++ script
        var sound3 = 'sounds/2000.wav'
        var tone = new Sound(sound2).play();

        response.sendFile(path.join(path.join(__dirname, 'views'), 'index.html'));
        response.status(200);
});

//Binding to localhost://portNum
server.listen(portNum,()=>{
        console.log('Express server started at port' + portNum);
});
